version: "2.1"

services:
  fizioterapia:
    image: fizioterapia
    build: .
    environment:
      NODE_ENV: production
      MASTER_KEY: cica
      JWT_SECRET: kutya
      PORT: 80
    ports:
      - 80:80

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
